-- ===========================================================
-- Squishy Society — seed data
-- Generated by scripts/migrate-products.js
-- Source: products.js + product-data.js at time of migration
--
-- Paste into: Supabase dashboard → SQL Editor → New query → Run
-- Safe to re-run (upserts on sku).
-- ===========================================================

begin;

-- sq-001 · Coconut Mochi Squeeze Ball
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-001', 'Coconut Mochi Squeeze Ball', 'mochi', 'Squishy, translucent mochi-style squeeze ball with a satisfying slow-rebound feel. Comes in six colours, 6cm each.',
  18.95, 7.16, 3.09,
  'AliExpress', 'https://www.aliexpress.com/item/1005012612601681.html',
  'images/coconut-mochi.png', '{}',
  'active',
  4.5, 13, '286+', '{"soft squish","comfortable to hold","durable construction","perfect size for transportation"}', '[{"text":"This stress ball is soft, squishy, and comfortable to hold, making it great for relieving stress or keeping your hands busy. The durable material feels high quality and returns to its original shape after squeezing.","author":"K***r","variant":"Blue 6cm"}]'::jsonb,
  false, false, 0
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- sq-002 · Glow-in-the-Dark Mochi Animal Pack
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-002', 'Glow-in-the-Dark Mochi Animal Pack', 'mochi', 'A bucket of assorted mini mochi-style animal squishies that glow in the dark — great as a party favour bundle or pick-and-mix item. Free shipping on this listing. Comes in four pack sizes, priced differently.',
  16.95, 7.61, 0,
  'AliExpress', 'https://www.aliexpress.com/item/1005006252139979.html',
  'images/mochi-glow-pack.png', '{}',
  'active',
  4.6, 288, '3,000+', '{"cute design","glow in the dark","nice and squishy","satisfactory"}', '[{"text":"As described. Good product. Nice variety of colors. Illuminates well in the dark. Various patterns. I recommend! The kids love it.","author":"k***k","variant":"24pcs without box"},{"text":"I bought 12 squishies, individually packaged, great! They are satisfying to squeeze. The quality is very satisfactory considering its price!","author":null,"variant":"12pcs without box"}]'::jsonb,
  false, false, 10
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- variants for sq-002
delete from product_variants where product_id = (select id from products where sku = 'sq-002');
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '12pcs without box', 7.61, 16.95, 0 from products where sku = 'sq-002';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '24pcs without box', 12.59, 27.95, 10 from products where sku = 'sq-002';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '24pcs with box', 14.25, 31.95, 20 from products where sku = 'sq-002';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '36pcs without box', 18.14, 39.95, 30 from products where sku = 'sq-002';

-- sq-011 · Mini Dumpling Keychain
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-011', 'Mini Dumpling Keychain', 'keychain', 'A soft plush dumpling-shaped keychain with a stitched-on smiley face — cute, pillowy, and instantly recognisable. Free shipping on this listing. Sold in packs of 1 to 5, priced per pack.',
  5.95, 2.12, 0,
  'AliExpress', 'https://www.aliexpress.com/item/1005009663405697.html',
  'https://ae-pic-a1.aliexpress-media.com/kf/Sa976459fb7724bf1bca6e153a425a8ebg.png', '{"https://ae-pic-a1.aliexpress-media.com/kf/S641d13301ae042999bbc1dc1edd2bb80K_480x480q75.jpg_.avif","https://ae-pic-a1.aliexpress-media.com/kf/S06ecd71dedef49a2b19caca6ec0d414fY_480x480q75.jpg_.avif","https://ae-pic-a1.aliexpress-media.com/kf/S054e9426d16c4b61a71f70b3e2c4a753s_480x480q75.jpg_.avif"}',
  'active',
  4.9, 65, '700+', '{"cute design","matches description","comfortable to use","excellent value for money"}', '[{"text":"Stunning Chinese dumpling-shaped keychain, and with the little eyes it''s even cuter... fast shipping and a reliable seller.","author":null,"variant":"White 3pcs"},{"text":"Very, very beautiful to look at and also incredibly comfortable, easy to wash, and it''s definitely worth more than the money!","author":null,"variant":"White 5pcs"}]'::jsonb,
  false, false, 20
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- variants for sq-011
delete from product_variants where product_id = (select id from products where sku = 'sq-011');
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, 'White 1pcs', 2.12, 5.95, 0 from products where sku = 'sq-011';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, 'White 2pcs', 3.01, 8.95, 10 from products where sku = 'sq-011';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, 'White 3pcs', 4.27, 11.95, 20 from products where sku = 'sq-011';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, 'White 4pcs', 4.95, 13.95, 30 from products where sku = 'sq-011';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, 'White 5pcs', 5.75, 15.95, 40 from products where sku = 'sq-011';

-- sq-013 · Mini Food Charm Keychain Set
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-013', 'Mini Food Charm Keychain Set', 'keychain', 'A set of tiny food-shaped squish charms — pancake stack, soft-boiled eggs, a mini cake, a dumpling — on ball-chain keyring clips. Sold in sets of 5 or 20.',
  8.95, 1.42, 0,
  null, null,
  'https://ae-pic-a1.aliexpress-media.com/kf/Sfa7d655094a94f7297981ec2bab662aeq.jpg_480x480q75.jpg_.avif', '{"https://ae-pic-a1.aliexpress-media.com/kf/Sb55f345c0fc14cb88d140810710f1cceD.jpg","https://ae-pic-a1.aliexpress-media.com/kf/S3676e3ce031d43a4b744be26464cd1feH.jpg","https://ae-pic-a1.aliexpress-media.com/kf/Sfa7d655094a94f7297981ec2bab662aeq.jpg"}',
  'active',
  4.7, 264, '4,000+', '{"cute design","satisfactory","great value for price","poor quality construction"}', '[]'::jsonb,
  false, false, 30
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- sq-015 · Cartoon Bear Squeak Keychain
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-015', 'Cartoon Bear Squeak Keychain', 'keychain', 'Soft bear pendant with a built-in squeak. Clips onto a bag strap or keyring.',
  8.95, 1.42, 0,
  null, null,
  'https://ae-pic-a1.aliexpress-media.com/kf/Seabcbe1ddb33471abf6993096cf1e09c9.jpg', '{"https://ae-pic-a1.aliexpress-media.com/kf/Seabcbe1ddb33471abf6993096cf1e09c9.jpg","https://ae-pic-a1.aliexpress-media.com/kf/S05babd47660f4f308ea1b7745727b54en.jpg","https://ae-pic-a1.aliexpress-media.com/kf/S4e8909d64783449ab676198adec4b993p.jpg"}',
  'active',
  4.8, 87, '600+', '{"very cute","cute","small","super cute"}', '[]'::jsonb,
  false, false, 40
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- sq-016 · Star Plush Squeak Keychain
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-016', 'Star Plush Squeak Keychain', 'keychain', 'Plush star charm with a gentle squeak — the cheapest way to add something soft to a backpack.',
  7.95, 1.42, 0,
  null, null,
  'https://ae-pic-a1.aliexpress-media.com/kf/Sfc0f13ce3c7b41829d24738ff42e4d29x.jpg_480x480q75.jpg_.avif', '{"https://ae-pic-a1.aliexpress-media.com/kf/Sfc0f13ce3c7b41829d24738ff42e4d29x.jpg","https://ae-pic-a1.aliexpress-media.com/kf/S5a9569d8f8bb408983e9d7182c8205d9p.jpg","https://ae-pic-a1.aliexpress-media.com/kf/S98ba369696b546e8bb0a0a465a61474cO.jpg"}',
  'active',
  4.8, 93, '500+', '{"cute","makes sound","nice","good quality"}', '[]'::jsonb,
  false, false, 50
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- sq-018 · Keyboard Clicker Fidget Keychain
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-018', 'Keyboard Clicker Fidget Keychain', 'keychain', 'Pastel mechanical-style keycaps on a keyring, purely for clicking. Comes as a single cube, a row of four, a cross of five, or a full 3x3 grid of nine. Free shipping on this listing.',
  7.95, 2.01, 0,
  'AliExpress', 'https://www.aliexpress.com/item/1005010788802674.html',
  'https://ae-pic-a1.aliexpress-media.com/kf/Sa85a5ce826ca49a2b109c61aa8b614edt.png', '{"https://ae-pic-a1.aliexpress-media.com/kf/Sa85a5ce826ca49a2b109c61aa8b614edt.png","https://ae-pic-a1.aliexpress-media.com/kf/Sb674556e92ad4a209849363cce3cad01n.png","https://ae-pic-a1.aliexpress-media.com/kf/S86d8facc1eaf4d78a6c5455f36b14a733.png"}',
  'active',
  4.8, 116, '2,000+', '{"satisfying click","accurate depiction","nice sound and feel","perfect"}', '[{"text":"It has a loop attached, so you can use it as a keyring! I remove the ring and place it on the desk to work on it. The switch has a nice clicky sound and a satisfying pressing feel that makes you want to keep touching it!","author":null,"variant":"4 Key"},{"text":"I love it. Its so satisfying and if you want, you can take off keys and switch them around. I recommend this.","author":null,"variant":"1 Key"}]'::jsonb,
  false, false, 60
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- variants for sq-018
delete from product_variants where product_id = (select id from products where sku = 'sq-018');
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '1 Key', 2.01, 7.95, 0 from products where sku = 'sq-018';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '4 Key', 3.21, 10.95, 10 from products where sku = 'sq-018';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '5 Key', 4.13, 12.95, 20 from products where sku = 'sq-018';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '9 Key', 4.72, 14.95, 30 from products where sku = 'sq-018';

-- sq-019 · Clear Mochi Squeeze Blob
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-019', 'Clear Mochi Squeeze Blob', 'mochi', 'Translucent mochi blob that squashes flat and slowly reforms. The see-through version of the classic mochi squish.',
  18.95, 6.63, 0,
  null, null,
  'https://ae-pic-a1.aliexpress-media.com/kf/Sb90d248920754776bb465dfaaaa86a13n.png_480x480.png_.avif', '{"https://ae-pic-a1.aliexpress-media.com/kf/Sb90d248920754776bb465dfaaaa86a13n.png","https://ae-pic-a1.aliexpress-media.com/kf/S2f53e5e60eee4e65bd416c741f77441bw.png","https://ae-pic-a1.aliexpress-media.com/kf/S366088ff899c4cf99c1bb8a271e5b5665.png"}',
  'active',
  4.9, 656, '5,000+', '{"very soft","pleasant coconut smell","satisfying to mold and shape","super moldable"}', '[]'::jsonb,
  false, false, 70
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- sq-020 · Pink Ice Ball Mochi Squish
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-020', 'Pink Ice Ball Mochi Squish', 'mochi', 'Soft pink maltose-style ball with a slow rebound and a slightly tacky, ice-like surface.',
  14.95, 5.06, 0,
  null, null,
  'https://ae-pic-a1.aliexpress-media.com/kf/Scbd5587abf1d47d4922220046474e2954.jpg_480x480q75.jpg_.avif', '{"https://ae-pic-a1.aliexpress-media.com/kf/Scbd5587abf1d47d4922220046474e2954.jpg","https://ae-pic-a1.aliexpress-media.com/kf/Sba0ac03bae944c9082058a06dac2c5c5y.jpg","https://ae-pic-a1.aliexpress-media.com/kf/S6cf372cfe4c54138b03d6267246157398.jpg"}',
  'active',
  4.9, 686, '5,000+', '{"satisfying","pleasant to use","firm texture","good texture"}', '[]'::jsonb,
  false, false, 80
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- sq-021 · Strawberry Mochi Squeeze Toy
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-021', 'Strawberry Mochi Squeeze Toy', 'mochi', 'Strawberry-shaped mochi squish built for hard squeezing — marketed squarely at stress relief.',
  15.95, 5.28, 0,
  null, null,
  'https://ae-pic-a1.aliexpress-media.com/kf/S0bdc6f4eb19445f38eed9512c2386ab6i.png_480x480.png_.avif', '{"https://ae-pic-a1.aliexpress-media.com/kf/S0bdc6f4eb19445f38eed9512c2386ab6i.png","https://ae-pic-a1.aliexpress-media.com/kf/Seada1706c4104598a4260f0e3436497eQ.png","https://ae-pic-a1.aliexpress-media.com/kf/Sce50308d17644db4b2e46e4243206bb5n.png"}',
  'active',
  4.4, 454, '5,000+', '{"soft and pliable","pleasant to touch","unpleasant smell","fun to play with"}', '[]'::jsonb,
  false, false, 90
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- sq-022 · Blue Maltose Mochi Ball
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-022', 'Blue Maltose Mochi Ball', 'mochi', 'Transparent blue maltose ball with a quick rebound. Heavier in the hand than it looks.',
  17.95, 5.96, 0,
  null, null,
  'https://ae-pic-a1.aliexpress-media.com/kf/S2e9a08405d994142813ae55d1e3a851f3.jpg_480x480q75.jpg_.avif', '{"https://ae-pic-a1.aliexpress-media.com/kf/Sff697d8096c7443c8d6484cbee581b5b6.jpg","https://ae-pic-a1.aliexpress-media.com/kf/Sa2e062ea8d3340c28bf92c9855c32b83m.jpg","https://ae-pic-a1.aliexpress-media.com/kf/S9c48f246f79e48f3b56401919e4fd85ab.jpg"}',
  'active',
  4.4, 727, '5,000+', '{"soft texture","satisfactory quality","aesthetically pleasing","not durable"}', '[]'::jsonb,
  false, false, 100
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- sq-023 · Mochi Animal Mega Pack (50pc)
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-023', 'Mochi Animal Mega Pack (50pc)', 'mochi', 'Fifty assorted mini mochi animals in one bag. Built for party favours, classroom prizes, or a pick-and-mix display.',
  44.95, 19.53, 0,
  null, null,
  'https://ae-pic-a1.aliexpress-media.com/kf/Sd136312a9b8b47ac8b7f63028b5a3cf5I.jpg_480x480q75.jpg_.avif', '{"https://ae-pic-a1.aliexpress-media.com/kf/S3b94677f8a984db3af2669687bfb6a3fZ.jpg","https://ae-pic-a1.aliexpress-media.com/kf/S9446706fd0044ff28dfd2cd03123aa09u.jpg","https://ae-pic-a1.aliexpress-media.com/kf/S35132d421b6049cf8ef7c254e290f4b0W.jpg"}',
  'active',
  4.4, 337, '3,000+', '{"cute","poor quality","fast delivery","as advertised"}', '[]'::jsonb,
  true, false, 110
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- sq-063 · Rainbow Prism Cube
insert into products (
  sku, name, category, description,
  price, supplier_cost, shipping_cost,
  supplier_name, supplier_url,
  image, gallery,
  status,
  source_rating, source_reviews, source_orders, source_tags, source_quotes,
  is_mystery, is_new_drop, sort_order
) values (
  'sq-063', 'Rainbow Prism Cube', 'prism', 'A solid crystal cube that splits light into shifting rainbow colour as you turn it in your hand — more hypnotic than squishy, for anyone who likes a visual fidget as much as a tactile one. Comes in four sizes.',
  21.95, 7.4, 3.12,
  'AliExpress', 'https://www.aliexpress.com/item/1005005399618112.html',
  'https://ae-pic-a1.aliexpress-media.com/kf/Sc8944e13c9ee46b18de226cad1983ac5H.jpg_480x480q75.jpg_.avif', '{"https://ae-pic-a1.aliexpress-media.com/kf/Sc8944e13c9ee46b18de226cad1983ac5H.jpg_480x480q75.jpg_.avif","https://ae-pic-a1.aliexpress-media.com/kf/S108b6ca87a2046de9084650d144d013cN.jpg_480x480q75.jpg_.avif","https://ae-pic-a1.aliexpress-media.com/kf/S23661bad086c4211b19864843039b99dA.jpg_480x480q75.jpg_.avif"}',
  'active',
  4.4, 72, '600+', '{"solid glass","excellent quality","does not mix colors","exactly as described","well protected packaging","looks great"}', '[{"text":"Perfect thing on the work table! Made of glass, not plastic — that''s a second one I''ve ordered.","author":"R***a","variant":"30mm"},{"text":"Solid glass and very much like the image. It''s like a CMY/RGB cube, not a prism — recommended if that''s what you''re after.","author":"a***r","variant":"60mm"}]'::jsonb,
  false, true, 120
)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  supplier_cost = excluded.supplier_cost,
  shipping_cost = excluded.shipping_cost,
  supplier_name = excluded.supplier_name,
  supplier_url = excluded.supplier_url,
  image = excluded.image,
  gallery = excluded.gallery,
  source_rating = excluded.source_rating,
  source_reviews = excluded.source_reviews,
  source_orders = excluded.source_orders,
  source_tags = excluded.source_tags,
  source_quotes = excluded.source_quotes,
  is_mystery = excluded.is_mystery,
  is_new_drop = excluded.is_new_drop,
  sort_order = excluded.sort_order;

-- variants for sq-063
delete from product_variants where product_id = (select id from products where sku = 'sq-063');
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '30mm', 7.4, 21.95, 0 from products where sku = 'sq-063';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '40mm', 11.89, 31.95, 10 from products where sku = 'sq-063';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '50mm', 16.29, 40.95, 20 from products where sku = 'sq-063';
insert into product_variants (product_id, label, variant_cost, price, sort_order)
select id, '60mm', 25.19, 58.95, 30 from products where sku = 'sq-063';

commit;

-- 13 products, 17 priced variants
